include:
  - kea-stork.yaml
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1000             # Set your user ID
      - PGID=1000             # Set your group ID
      - SERVERPORT=51820      # Default WireGuard port
    #  - PEERS=5               # Number of WireGuard peers
      - DEBUG=1               # Enable debug logging
      - PEERDNS=1.1.1.1       # DNS resolver for clients
      - TZ=${TZ}
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./wireguard:/config/wg_confs
    cap_add:
      - NET_ADMIN             # Required for modifying network settings
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      local:
        ipv4_address: ${WG_BRIDGE_IP}
    ports:
      - "51820:51820/udp"     # WireGuard default port
    #network_mode: host
    restart: always

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    #depends_on:
    #  - wireguard             # Delay start until WireGuard is ready
    environment:
      - UPSTREAM1=https://1.1.1.1/dns-query
      - UPSTREAM2=https://9.9.9.9:5053/dns-query
      - PORT=53
      - TZ=${TZ}
      - DEBIAN_FRONTEND=noninteractive
    network_mode: host
    restart: always

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    environment:
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY} # Use your Tailscale auth key
      - TAILSCALE_HOSTNAME=${HOSTNAME}
      - TAILSCALE_UP=true
      - TZ=${TZ}
      - DEBIAN_FRONTEND=noninteractive
    cap_add:
      - NET_ADMIN                 # Required for modifying network settings
      - SYS_MODULE
    ports:
      - "41641:41641"             # Tailscale's default port for control
    network_mode: host
    restart: always

networks:
  local:
    name: local
    driver: bridge
    ipam:
      config:
        - subnet: ${WG_BRIDGE_SUBNET}  # Define the subnet for the network
          gateway: ${WG_BRIDGE_GATEWAY}     # Define the gateway for the network