services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -U kea -d kea -c 'SELECT version FROM schema_version'"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./database:/var/lib/postgresql
      - type: bind
        source: ./initdb  # Database setup script from kea for the first run
        target: /docker-entrypoint-initdb.d
    networks:
      kea-20: 

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1000             # Set your user ID
      - PGID=1000             # Set your group ID
      - SERVERPORT=51820      # Default WireGuard port
      #- PEERS=5               # Number of WireGuard peers
      - DEBUG=1               # Enable debug logging
      - PEERDNS=1.1.1.1       # DNS resolver for clients
    volumes:
      - ./wireguard:/config/wg_confs
    cap_add:
      - NET_ADMIN             # Required for modifying network settings
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    #ports:
    #  - "51820:51820/udp"     # WireGuard default port
    #network_mode: host
    networks:
      kea-10: 
        ipv4_address: ${WG_IP4} 
    restart: always

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    #depends_on:
    #  - wireguard             # Delay start until WireGuard is ready
    environment:
      - UPSTREAM1=https://1.1.1.1/dns-query
      - UPSTREAM2=https://9.9.9.9:5053/dns-query
      - PORT=53
    networks:
      kea-10: 
        ipv4_address: ${DNS_IP4} 
    restart: always

  kea:
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:${KEA_VERSION}
    container_name: kea
    depends_on:
      db:
        condition: service_healthy  # Delay start until the database is healthy
    networks:
      kea-10: 
        ipv4_address: ${KEA_IP4} 
      kea-20:
    volumes:
      - type: bind
        source: ./kea  # Configuration files for Kea
        target: /etc/kea
      - ./kea/var:/var/lib/kea  # Persistent data
    restart: always

networks:
  kea-10:  # Network that binds container to host network interface.
    name: kea-10
    driver: ipvlan
    driver_opts:
      parent: ${ETH1}  # Host interface that Kea containers will use (eth1)
      ipvlan_mode: l3
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${SUBNET4}  # Subnet for Kea containers
          gateway: ${GATEWAY4}  # Gateway for Kea subnet
  kea-20:  # Internal network for communication with database
    name: kea-20

