services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql -U kea -d kea -c 'SELECT version FROM schema_version'"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./database:/var/lib/posgresql
      - type: bind
        source: ./initdb # database setup script from kea for first run
        target: /docker-entrypoint-initdb.d
    networks:
      kea-20-backend:

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    environment:
      - PUID=1000             # Set your user ID
      - PGID=1000             # Set your group ID
      - SERVERPORT=51820      # Default WireGuard port
      - DEBUG=1               # Enable debug logging
    volumes:
      - ./wireguard:/config/wg_confs
    cap_add:
      - NET_ADMIN              # Required for modifying network settings
    ports:
      - "51820:51820/udp"      # WireGuard default port
    networks:
      kea-10-ipvlan: # network that binds container to host network interface.
        ipv4_address: ${WG_IP4} # ip for kea4 server
    restart: always

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    depends_on: # delay start until wireguard is ready
      wireguard:
        condition: service_healthy
    environment:
      - UPSTREAM1=https://1.1.1.1/dns-query
      - UPSTREAM2=https://9.9.9.9:5053/dns-query
      - PORT=53
    ports:
      - "53:53/udp"
    networks:
      kea-10-ipvlan: # network that binds container to host network interface.
        ipv4_address: ${BIND_IP4} # ip for kea4 server
    restart: always

  kea:
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:${KEA_VERSION}
    container_name: kea
    depends_on: # delay start until database is ready
      db:
        condition: service_healthy
    networks:
      kea-10-ipvlan: # network that binds container to host network interface.
        ipv4_address: ${KEA_IP4} # ip for kea4 server
      kea-20-backend: # internal network for communication with database
    volumes:
      - type: bind
        source: ./kea # configuration files
        target: /etc/kea
      - ./kea/var:/var/lib/kea
    restart: always

networks:
  kea-10-ipvlan: # network that binds container to host network interface.
    name: kea-10-ipvlan
    driver: ipvlan
    driver_opts:
      parent: ${ETH} #  host interface that kea containers will use !!!!!!
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${SUBNET4} # subnet for kea4 server
  kea-20-backend: # internal network for communication with database
    name: kea-20-backend
