datasources:
  - name: MyDataSource
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
      tlsSkipVerify: true
    secureJsonData:
      token: my-secret-token
    version: 1
    editable: true
